### ISSUE TITLE
allow loading tab immedietly

### ISSUE THREAD

**Issue by fennectech** [Suyooo/firefox-dailytab#1]
id like a way to make tabs automaticly load even if the user does not click them

**Comment by Suyooo** [comment]
Added for v1.2.0, and it seems it's already up on the official site as well so you should be able to update right away. Thank you for the suggestion!

![2024-11-10_11-46](https://github.com/user-attachments/assets/6c1f8825-48fa-4b64-8949-1d36191d196f)

**Comment by fennectech** [comment]
Congrats.   Thanks for adding it so insanely quickly!    I’ll let Firefox update itself and enable preloading on desktop.
